name: Build and Push FastAPI project to Docker

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-push:
    name: Build and Push FastAPI project
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: filtro_jwt
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 3
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Run python
      run: python test.py
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      uses: docker/build-push-action@v3
      with:
            context: .
            dockerfile: Dockerfile
            push: false
            tags: zafuog/fastapi_filtro:latest

    - name: Push Docker Image
      uses: docker/build-push-action@v3
      with:
            context: .
            dockerfile: Dockerfile
            push: true
            tags: zafuog/fastapi_filtro:latest
    
